[arch] new: 添加内核组件黑名单相关的文档 [scripts] misc: 添加ISTTY用于确定脚本是否跑在tty上
Signed-off-by: MATRIX-feather <midnightcarnival@outlook.com>

diff --git a/scripts/common/common b/scripts/common/common
--- a/scripts/common/common
+++ b/scripts/common/common
@@ -76,7 +76,10 @@ readonly PIDLOCKTARGET="/dev/shm/${FILEPREFIX}-lock-${APPNAME}"
 readonly AUTOTERMINAL="${AUTOTERMINAL:-false}"
 
 #是否为终端
-ISTERMINAL=false
+ISPIPE=false
+
+#是否为GUI（不是tty）
+ISTTY=false
 
 #处理SIGTERM
 trap "handle_term" SIGTERM
@@ -90,7 +93,7 @@ function on_term()
 
 function handle_term()
 {
-    if [ "${ISTERMINAL}" == "true" ];then
+    if [ "${ISPIPE}" == "false" ];then
         printf "\033[8D" #回到这一行的开头
     fi;
 
@@ -281,33 +284,78 @@ function checkLogName()
 
 checkLogName
 
+TERMINAL_EXEC="${TERMINAL_EXEC:-}"
+
+#检查是否为终端或者tty
 function checkTerminal()
 {
+    #检查tty
+    case "$(tty)" in
+        (/dev/tty/[1-9])
+            ISTTY="true"
+            ;;
+        
+        (*)
+            ISTTY="false"
+            ;;
+    esac
+
+    readonly ISTTY;
+
+    #检查终端
     #https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe
     #目前只需要检查stdout
     if [ -t 1 ];then
+        ISPIPE=false
         ISTERMINAL=true
     else
+        ISPIPE=true
         ISTERMINAL=false
+    fi;
 
-        if [ "${AUTOTERMINAL}" == true ];then
-            if [ -z "$DISPLAY" ];then
-                echo "没有设置环境变量DISPLAY，没法打开终端:(" >> "A_${APPNAME}_ERROR"
-                die 255 "没有设置DISPLAY" >&2
-            fi;
+    readonly ISPIPE;
+    readonly ISTERMINAL; #版本兼容
 
-            #移除pid以避免相关问题
-            removepid > /dev/null
-            x-terminal-emulator -e "$(readlink -f "${APPNAME}") $*" &
-            die 0 "已在新终端中打开脚本" >&2
-        fi;
+    #检查有没有x-terminal-emulator
+    if [ -z "${TERMINAL_EXEC}" ];then
+        if which x-terminal-emulator >/dev/null 2>/dev/null;then
+            TERMINAL_EXEC="x-terminal-emolator -e"
+        elif which gnome-terminal >/dev/null 2>/dev/null;then
+            TERMINAL_EXEC="gnome-terminal --"
+        else
+            die 255 "无法确定新终端开启方式，请手动指定TERMINAL_EXEC环境变量"
+        fi
     fi
 
-    readonly ISTERMINAL
     unset checkTerminal
 }
 
-checkTerminal "$@"
+checkTerminal
+
+function checkIfShouldStartInTerminal()
+{
+    if [ "${AUTOTERMINAL}" == true ] && [ "${ISPIPE}" == "true" ] || [ "${AUTOTERMINAL}" == true ] && [ "${ISTTY}" == "true" ];then
+        if [ "${ISTTY}" == "true" ];then
+            die 255 "This script or program cannot run in tty :("
+        fi
+
+        if [ -z "$DISPLAY" ];then
+            echo "没有设置环境变量DISPLAY，没法打开终端:(" >> "A_${APPNAME}_ERROR"
+            die 255 "没有设置DISPLAY" >&2
+        fi;
+
+        #移除pid以避免相关问题
+        removepid > /dev/null
+        log "正在新终端中启动脚本..."
+        ${TERMINAL_EXEC} "$(readlink -f "${APPNAME}")" "$@" || die 255 "未能在终端中启动脚本"
+        log "启动完成"
+        exit 0
+    fi;
+
+    unset checkIfShouldStartInTerminal
+}
+
+checkIfShouldStartInTerminal "$@"
 
 #初始化LOG文件
 if [ "${LOGTOFILE}" == "true" ];then
