[fix] yuanshen: 在checkTerminal中检查AUTOTERMINAL是否为true [enchance] yuanshen: 调整SIGTERM相关处理
Signed-off-by: MATRIX-feather <midnightcarnival@outlook.com>

diff --git a/yuanshen/common/common b/yuanshen/common/common
--- a/yuanshen/common/common
+++ b/yuanshen/common/common
@@ -73,15 +73,28 @@ readonly AUTOTERMINAL="${AUTOTERMINAL:-false}"
 ISTERMINAL=false
 
 #处理SIGTERM
-trap handle_term SIGTERM
-trap handle_term SIGINT
+trap "handle_term" SIGTERM
+trap "handle_term" SIGINT
 
-#handle_term，可以被脚本override
+#on_term，可以被脚本override
+function on_term()
+{
+    true
+}
+
 function handle_term()
 {
+    if [ "${ISTERMINAL}" == "true" ];then
+        printf "\033[8D" #回到这一行的开头
+    fi;
+
+    on_term || die "${RET_GENERIC_FAILED}" "脚本执行on_term时出现了问题"
+
     log "再见！"
     exit 0
 }
+
+readonly -f handle_term
 
 function log()
 {
@@ -226,11 +239,6 @@ function checkLogName()
 
 checkLogName
 
-#初始化LOG文件
-if [ "${LOGTOFILE}" == "true" ];then
-    log "PID为${PID}的${DISPLAYNAME}(${APPNAME})于$(date "+%Y-%m-%d %H:%M:%S")启动"
-fi
-
 function checkTerminal()
 {
     #https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe
@@ -240,15 +248,15 @@ function checkTerminal()
     else
         ISTERMINAL=false
 
-        if [ "${AUTOTERMINAL}" ];then
+        if [ "${AUTOTERMINAL}" == true ];then
             if [ -z "$DISPLAY" ];then
                 echo "没有设置环境变量DISPLAY，没法打开终端:(" >> "A_${APPNAME}_ERROR"
                 die 255 "没有设置DISPLAY" >&2
             fi;
 
             #移除pid以避免相关问题
-            removepid
-            x-terminal-emulator -e "$(readlink -f "$0") $*" & disown
+            removepid > /dev/null
+            x-terminal-emulator -e "$(readlink -f "${APPNAME}") $*" &
             die 0 "已在新终端中打开脚本" >&2
         fi;
     fi
@@ -258,3 +266,8 @@ function checkTerminal()
 }
 
 checkTerminal "$@"
+
+#初始化LOG文件
+if [ "${LOGTOFILE}" == "true" ];then
+    log "PID为${PID}的${DISPLAYNAME}(${APPNAME})于$(date "+%Y-%m-%d %H:%M:%S")启动"
+fi
